### ISSUE TITLE
Duplicate method, missing method, and method efficiency

### ISSUE THREAD

**Issue by elyisgreat** [kiprobinson/BigFraction#4]
I took a look again at your methods recently, and besides the modulo optimizations, I noticed a few things:

1. the `integralQuotient` method is identical to the `divideToIntegralValue` method. Why have both?

2. Greatest common factor (or greatest common divisor) is a function I use quite often. It is found in BigInteger but does not exist in BigFraction. A method for it could be easily written as for simplest form fractions, `gcf(a/b,c/d)=gcf(a,c)/lcm(b,d)`

3. Speaking of gcfs, I noticed that in the `pow` method, it returns reduced fractions, even though if a fraction a/b is already in simplest form, (a/b)^n is also in simplest form and needs no reduction. Why does the `pow` method need to reduce?

Keep up the good work!

**Comment by kiprobinson** [comment]
1. integralQuotient is static. I try to provide static versions of the basic math methods. So if it is more convenient you can do `BigFraction.integralQuotient(11, 2.5)`, rather than `BigFraction.valueOf(11).divideToIntegralValue(2.5)`.  Similar to how I have `BigFraction.sum(3, 0.5)` which is equivalent to `BigFraction.valueOf(3).add(0.5)`

2. I will look into it. I generally don't implement it if I don't understand the underlying math, so I'll have to wrap my head around what exactly the gcf of two fractions is. (Kind of like I had to for fraction division with remainder.)

3. `pow()` doesn't reduce. It passes `Reduced.YES` to the internal constructor, which tells it not to try to compute the gcf.

**Comment by kiprobinson** [comment]
I've committed an implementation of gcd() and lcm() methods.
