### ISSUE TITLE
github description bug, feature question, and request

### ISSUE THREAD

**Issue by elyisgreat** [kiprobinson/BigFraction#6]
It says on the main github page that the java7 branch compiles in Java 7 and also java 5-6. This is in fact not the case, as the Long.compare() method used by the LongFraction class does not exist before java 7. I often use the BigFraction class in Java 6, so it would be nice if it worked in that version.

I also noticed a lot of new features added. I noticed the roundToDenominator() method, however you can extend this to any value using `round(x,m)=round(x/m)*m`. m here is the increment to which you are rounding, and the single argument round() function rounds to integral value.

Another question I have is regarding the `()` syntax for repeating digits. Even though the parsers never handle it this way, I think a syntax like 0.1(6) is confusing, as it could be interpreted as 0.16... or 0.6. Is there a better syntax? Or do you think `()` is the best option?

**Comment by kiprobinson** [comment]
I'm not sure how `0.1(6)` could be interpreted as `0.6`. When I researched [ways of representing repeating decimals](https://en.wikipedia.org/wiki/Repeating_decimal#Notation), all the other methods involved typographic marks that you wouldn't be able to represent in unformatted text (or maybe you could represent it somehow with unicode characters, but it would be inconvenient). The parenthetical notation is easy to represent in plain ascii characters, so I went with that and documented it as best I could in the javadoc.

I'm not sure if I need yet more rounding functions, but I'll keep it in mind.

I'll try to look into Java 6 sometime this week. I have never actually tried it with Java 6 JDK.

**Comment by elyisgreat** [comment]
>I'm not sure how `0.1(6)` could be interpreted as `0.6`.

[Like this](http://www.wolframalpha.com/input/?i=0.1(6)). In the case where `()` is not explicitly meaning repeating decimal, it can be interpreted as multiplication. This is not a problem for your parser, however if I were to pass `0.1(6)` to an [algebraic expression class](http://projects.congrace.de/exp4j/) it would do the multiplication instead of throw an exception

```
import net.objecthunter.exp4j.*;
public class Test {
  public static void main(String[] args){
    Expression e = new ExpressionBuilder("0.1(6)").build();
    System.out.println(e.evaluate());//returns 0.6
    Expression f = new ExpressionBuilder("0.16\u0307").build();//throws an error
    System.out.println(f.evaluate());
  }
}
``` 

Using `\u0307` for combining dot and `\u0305` for combining bar work perfectly fine. I understand that it's not easy for everyone, and since `()` works unambiguously for the BigFraction parser you shouldn't change it. However support for forms like 0.13̅0̅5̅ or 0.13̇05̇ would be nice.

For rounding functions, given that your roundToDenominator function essentially performs the roundToValue function, I imagine these would not be too hard to implement.

```
//static versions of round to value
  public static BigFraction roundToValue(BigFraction toRound,BigFraction val){
    return roundToValue(toRound,val,RoundingMode.HALF_UP);
  }
  public static BigFraction roundToValue(BigFraction toRound,BigFraction val,RoundingMode roundingMode){
    return BigFraction.valueOf((toRound.divide(val)).round(roundingMode)).multiply(val);
  }
```

Speaking of roundToDenominator, why does it round to integer? I expected it to round to fraction...

**Comment by kiprobinson** [comment]
I've added a `java6` branch that will compile in Java6. I see what you mean about `0.1(6)`, but I don't think I want to implement unicode support. You only get the repeating decimal syntax if you ask for it, at which point you could write logic to change it as needed. If you're taking user input and passing it into the string constructor, you can also run a check to make sure it doesn't use repeating decimal syntax if you don't want to allow it.

For roundToDenominator, I think I was trying to solve a problem like- if every pizza has 8 slices, and we purchased 6 pizzas for 20 people, what's the minimum number of slices should each person get? Answer is 6/20, floor-rounded to nearest eighth (2/8) and taking the numerator- 2 slices. If I returned the fraction it would be reduced as 1/4, and you'd have to do additional math to get the 2 that you really wanted. In retrospect, roundToDenominator is solving a pretty specific problem that the user could solve on their own without the function pretty easily. But I don't want to deprecate or change what the function does either, so that I don't break anything. I'll probably eventually add something like roundToValue function that you propose.

**Comment by kiprobinson** [comment]
FYI- Just added a `roundToNumber()`, which rounds to the nearest multiple of a given number. No plans to add unicode for repeating fractions or to change roundToDenominator().
